### PR TITLE
Add auto-update-enabled and auto-update-disabled views on the plugins screen

### LINKED ISSUE #17: add views for auto-updates enabled/disabled
This would allow users to more easily manage their lists of plugins that have auto-updates enabled/disabled.

enabled-disabled-views

PR coming shortly.

### PR DESCRIPTION
**Pull request by pbiron**
Fixes #17

### CODE REVIEW

**Comment by pbiron** [comment]
There are inline comments and notes in the DocBlocks of the 2 functions this PR adds that describe where changes will be needed if/when this is merged into core.

Adding the views is straightforward, with core's `views_plugins` filter.

Limiting the plugins displayed in the list table when one of those views is current is a bit of a hack, but since the readme says

> with potentially some hacks when needed

I guess it's OK :-)

The hack uses core's `pre_current_active_plugins` action to override what happens in `WP_Plugins_List_Table::prepare_items()` when one of the links in the views is clicked on.

**Comment by pbiron** [comment]
Also, the `hack` will not be necessary once the `auto-update-enabled` and `auto-update-disabled` "status" are incorporated into the code in `WP_Plugins_List_Table::prepare_items()`.

**Review by pbiron — COMMENTED** [review]
The change on line 31 was **not** intentional....there must be a whitespace difference between that line in `master` and in the plugin in the .org repo.

**Comment by audrasjb** [comment]
Thanks @pbiron !
Yeah, I know for the hack, no worries.
Also, worth noting the feature is already implemented in the Trac ticket: https://core.trac.wordpress.org/attachment/ticket/48850/48850.11.diff

Worth also adding it to the Feature Plugin, thanks!
Will test the patch later today,

Cheers 🍻
Jb

**Comment by pbiron** [comment]
> Also, worth noting the feature is already implemented in the Trac ticket: https://core.trac.wordpress.org/attachment/ticket/48850/48850.11.diff

Cool, didn't realize that.

> Worth also adding it to the Feature Plugin, thanks!
> Will test the patch later today,

Would it help if I updated the PR to more closely match what is in the diff on Trac?

**Comment by pbiron** [comment]
And shame on me for using the right hook to add the views in multisite and for adding them on the non-network plugins screen in multisite :-)  Me, of all people, should have known better :-)

I'll update the PR accordingly, but will wait to hear back from you about whether I should also make things more closely match what's in the diff on Trac.

**Comment by audrasjb** [comment]
That's not mandatory, but it would be a nice to have indeed :-)

**Comment by pbiron** [comment]
PR updated:

1. uses the same strings and array indexes for the views as in https://core.trac.wordpress.org/attachment/ticket/48850/48850.11.diff
2. in multisite, only adds the views on the `plugins-network` screen
3. adds the `wp-autoupdate` domain to the `_n()` calls for the strings

**Comment by audrasjb** [comment]
I made some fixes (in a PR in your branch):
- use `auto-update-enabled` and `auto-update-disabled` custom statuses everywhere otherwise it wont work
- fix typo on `$wp_auto_update_plguins`  variable :)
- to get the number in `$enabled_count`, we have to use only plugins that exists in the WP installation. Indeed some of them could be deleted and still be in `wp_auto_update_plugins` site option :D

**Comment by pbiron** [comment]
PR updated.

- this uses status_links array indices `autoupdate_enabled` and `autoupdate_disabled` throughout, as those are what is used in the patch on Trac.  My previous commit forgot to change that in one place
- corrects the typo in `$wp_autoupdates_plugin` variable name
- uses `array_intersect()` to strip from the value stored in the `wp_auto_update_plugins` site option plugins that are no longer installed (rather than iterating over the array and incrementing the count as you suggested).

**Comment by audrasjb** [comment]
Thanks for the update Paul!

**Comment by pbiron** [comment]
2 things before you merge this:

1. after #32 is merged, then removing "deleted" plugins from the counts for the views isn't strictly necessary...but I think it's still a good idea to leave that code in for now
2. if the count for a view is 0, should that view not be added?  Generally speaking, that's how `most` of the core list tables work.  For instance, if all posts have the `publish` status, the views do not include `Pending (0)`, `Draft (0)`.  The one exception to that I know of is the `Privacy Tools` (see https://core.trac.wordpress.org/ticket/47495)

**Comment by audrasjb** [comment]
Thanks Paul.
I'm fine with (1) for the moment and let's handle (2) in a separated issue :)

**Pull request merged**
